NIFTY_50 = [
    "RELIANCE", "TCS", "HDFCBANK", "BHARTIARTL", "ICICIBANK",
    "INFY", "SBIN", "HINDUNILVR", "ITC", "LT",
    "BAJFINANCE", "KOTAKBANK", "SUNPHARMA", "HCLTECH", "MARUTI",
    "AXISBANK", "ASIANPAINT", "TITAN", "BAJAJFINSV", "NTPC",
    "ADANIENT", "ONGC", "ULTRACEMCO", "POWERGRID", "TATAMOTORS",
    "NESTLEIND", "WIPRO", "M&M", "JSWSTEEL", "TATASTEEL",
    "COALINDIA", "ADANIPORTS", "TECHM", "INDUSINDBK", "GRASIM",
    "HINDALCO", "DIVISLAB", "BRITANNIA", "EICHERMOT", "CIPLA",
    "DRREDDY", "BPCL", "BAJAJ-AUTO", "HDFCLIFE", "SBILIFE",
    "APOLLOHOSP", "TATACONSUM", "UPL", "HEROMOTOCO", "LTIM",
]
