"""initial schema

Revision ID: 13b0e5f8e76d
Revises: 
Create Date: 2026-04-14 04:13:11.351076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '13b0e5f8e76d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('instrument_token', sa.BigInteger(), nullable=False),
    sa.Column('exchange_token', sa.BigInteger(), nullable=False),
    sa.Column('tradingsymbol', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('segment', sa.String(length=20), nullable=True),
    sa.Column('instrument_type', sa.String(length=20), nullable=True),
    sa.Column('lot_size', sa.Integer(), nullable=False),
    sa.Column('tick_size', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=True),
    sa.Column('last_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_token')
    )
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('kite_api_key', sa.String(length=255), nullable=True),
    sa.Column('kite_api_secret', sa.String(length=255), nullable=True),
    sa.Column('kite_access_token', sa.String(length=255), nullable=True),
    sa.Column('kite_token_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('gemini_api_key', sa.String(length=255), nullable=True),
    sa.Column('anthropic_api_key', sa.String(length=255), nullable=True),
    sa.Column('settings_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('stocks')
    # ### end Alembic commands ###
