"""add portfolio analyses table

Revision ID: 1b8b2bd39319
Revises: 57ce8052ebba
Create Date: 2026-04-15 07:08:34.523676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1b8b2bd39319'
down_revision: Union[str, None] = '57ce8052ebba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_analyses',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('holdings_count', sa.Integer(), nullable=False),
    sa.Column('sell_count', sa.Integer(), nullable=False),
    sa.Column('hold_count', sa.Integer(), nullable=False),
    sa.Column('watchful_count', sa.Integer(), nullable=False),
    sa.Column('overall_health', sa.String(length=20), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('raw_prompt_data', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_analyses')
    # ### end Alembic commands ###
