"""add_news_sentiment_cache_table

Revision ID: 1dfd940b940e
Revises: c3a1f5e82d01
Create Date: 2026-04-16 18:24:26.387644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1dfd940b940e'
down_revision: Union[str, None] = 'c3a1f5e82d01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_sentiment_cache',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('sentiment', sa.String(length=20), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_sentiment_cache_symbol'), 'news_sentiment_cache', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_news_sentiment_cache_symbol'), table_name='news_sentiment_cache')
    op.drop_table('news_sentiment_cache')
    # ### end Alembic commands ###
