"""add daily_news_reports table

Revision ID: 55905dcb95ea
Revises: 1dfd940b940e
Create Date: 2026-04-16 19:00:20.856724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '55905dcb95ea'
down_revision: Union[str, None] = '1dfd940b940e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_news_reports',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('total_headlines', sa.Integer(), nullable=False),
    sa.Column('companies_found', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_news_reports_report_date'), 'daily_news_reports', ['report_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_daily_news_reports_report_date'), table_name='daily_news_reports')
    op.drop_table('daily_news_reports')
    # ### end Alembic commands ###
