"""add fundamentals and strategies tables

Revision ID: a7641e406404
Revises: 1b8b2bd39319
Create Date: 2026-04-15 07:21:32.531163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a7641e406404'
down_revision: Union[str, None] = '1b8b2bd39319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_fundamentals',
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('cmp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ttm_pe', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('forward_pe', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revenue_growth_1y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('eps_growth_1y', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('earnings_growth_forward', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('net_profit_margin', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_fundamentals_symbol'), 'stock_fundamentals', ['symbol'], unique=True)
    op.create_table('strategies',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('strategy_type', sa.String(length=50), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('strategies')
    op.drop_index(op.f('ix_stock_fundamentals_symbol'), table_name='stock_fundamentals')
    op.drop_table('stock_fundamentals')
    # ### end Alembic commands ###
