"""add stock_notes table

Revision ID: af562b37cd5a
Revises: 2c23d747fb54
Create Date: 2026-04-15 08:53:08.024126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'af562b37cd5a'
down_revision: Union[str, None] = '2c23d747fb54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_notes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'symbol', name='uq_user_symbol_note')
    )
    op.create_index(op.f('ix_stock_notes_symbol'), 'stock_notes', ['symbol'], unique=False)
    op.create_index(op.f('ix_stock_notes_user_id'), 'stock_notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_notes_user_id'), table_name='stock_notes')
    op.drop_index(op.f('ix_stock_notes_symbol'), table_name='stock_notes')
    op.drop_table('stock_notes')
    # ### end Alembic commands ###
