"""add investment_decisions table

Revision ID: bbca204e9fa0
Revises: af562b37cd5a
Create Date: 2026-04-16 08:01:02.037409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bbca204e9fa0'
down_revision: Union[str, None] = 'af562b37cd5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investment_decisions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('exchange', sa.String(length=10), nullable=False),
    sa.Column('verdict', sa.String(length=20), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('strategies_passed', sa.Integer(), nullable=False),
    sa.Column('strategies_total', sa.Integer(), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_decisions_symbol'), 'investment_decisions', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_investment_decisions_symbol'), table_name='investment_decisions')
    op.drop_table('investment_decisions')
    # ### end Alembic commands ###
